# Generated by Django 4.2.5 on 2023-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/author/%Y/%m')),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/book/%Y/%m')),
                ('finish', models.BooleanField(default=False)),
            ],
        ),
    ]
